base/urls.py
from django.urls import path
from base import views

app_name = 'base'

urlpatterns = [
    path('', views.home_page, name='home'),
]

controller/urls.py
from django.urls import path
from controller import views

app_name = 'controller'

urlpatterns = [
    path('<int:controller_id>/', views.add_to_database, name='add_to_database'),
    path('detail/<int:controller_id>/', views.view_controller_detail, name='controller_detail'),
]

# urlpatterns = [
#     path('/<int:controller_id>/<float:rv>/<float:rc>/<float:ap>/<float:rp>/', views.add_to_database, name='add_to_database'),
#     path('/<int:controller_id>/<float:rv>/<float:rc>/<float:ap>/<float:rp>/<str:pc>/', views.add_to_database, name='add_to_database_with_phase_connection'),
# ]

lrvlvf/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls', namespace='base')),
    path('controller/', include('controller.urls', namespace='controller'))
]

base/models.py
from django.db import models

# Create your models here.

controller/models.py
from django.db import models
from django.db.models.fields import DecimalField

# Create your models here.

class Controller(models.Model):
    name = models.CharField(db_index=True, max_length=200)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('created',)
    
    def __str__(self) -> str:
        return f'Controller: {self.name}'


class ElectricalParameters(models.Model):
    rms_voltage = models.DecimalField(max_digits=10, decimal_places=5)
    rms_current = models.DecimalField(max_digits=10, decimal_places=5)
    active_power = models.DecimalField(max_digits=10, decimal_places=5)
    reactive_power = models.DecimalField(max_digits=10, decimal_places=5)
    phase_connection = models.CharField(max_length=1, blank=True)
    controller = models.ForeignKey(Controller, on_delete=models.CASCADE, related_name='parameters')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('controller','-created',)
    
    def __str__(self) -> str:
        return f'Parameters for Controller: {self.controller.name} date: {self.created}'

base/views.py
from django.shortcuts import render

from controller.models import ElectricalParameters as E, Controller as C

# Create your views here.

def home_page(request):
    controller = C.objects.all()
    parameters = []
    for p in controller:
        if E.objects.filter(controller=p).exists():
            parameters.append(E.objects.filter(controller=p).order_by('-created')[0])
    
    return render(request,
                'base/home.html',
                {'parameters': parameters,})

controller/views.py
from django.contrib import messages
from django.shortcuts import redirect, render, get_object_or_404
from django.views.decorators.http import require_GET, require_http_methods
from .models import Controller, ElectricalParameters

# Create your views here.

def add_to_database(request, controller_id):
    controller = get_object_or_404(Controller, id=controller_id)
    rms_voltage = request.GET.get('v', '')
    rms_current = request.GET.get('i', '')
    active_power = request.GET.get('p', '')
    reactive_power = request.GET.get('q', '')
    phase_connection = request.GET.get('abc', '')
    if all([rms_voltage, rms_current, active_power, reactive_power]):
        parameter = ElectricalParameters(
                controller=controller,
                rms_voltage=float(rms_voltage), 
                rms_current=float(rms_current), 
                active_power=float(active_power),
                reactive_power=float(reactive_power),
                phase_connection=phase_connection,
                )
        parameter.save()
        messages.success(request, f"{controller}'s parameter updated!")
    else:
        messages.error(request, "Parameter update failed!")
    return redirect('base:home')


def view_controller_detail(request, controller_id):
    controller = get_object_or_404(Controller, id=controller_id)
    parameters = ElectricalParameters.objects.filter(controller=controller)[:10]
    master = False
    if controller_id == 1:
        master = True

    return render(request,
                'controller/detail.html',
                {'controller': controller,
                'parameters': parameters,
                'master': master})

base/templates/base/base.html
{% load bootstrap5 %}
{% load static %}
{% load fontawesome_5 %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} {% endblock %}</title>

    <!--Custom Font Import-->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Fjalla+One">

    <!--Bootstrap and FontAwesome-->
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    {% fontawesome_5_static %}

    <!--Custom CSS-->
    <link rel="stylesheet" type="text/css" href="{% static 'base/css/base.css' %}" />

    {% block extraheadelements %}{% endblock %}
</head>
<body>
    <header></header>
    <main>
        <div class="container py-4">
            <header class="pb-1 mb-4 border-bottom">
                <h2>Load Unbalance Reduction in Low Voltage Feeder</h2>
                <small class="text-muted">by dynamic switching of Residential customres among three phase</small>
            </header>

            <div class="row">
                <div class="col-md-12">
                    {% if messages %}
                    {% for message in messages %}
                    <div class="alert alert-{{ message.tags }}">
                        {{ message }}
                    </div>
                    {% endfor %}
                    {% endif %}
                </div>
            </div>

            <div class="p-5 mb-4 bg-light rounded-3">
                {% block content %} {% endblock %}
              </div>

            <footer class="footer mt-auto py-3 bg-light">
            <div class="container">
                <span class="text-muted inline">Yubraj Chimouriya, Aship Chaudhary, Abhijeet Chaudhary</span>
                <span class="text-muted inline" style="float: right;">Supervised by: Dr. Samundra Gurung</span>
            </div>
            </footer>
        </div>
        {% block extra %}{% endblock extra %}
    </main>
    <footer></footer>
</body>
</html>

base/templates/base/home.html
{% extends 'base/base.html' %}
{% load static %}

{% block content %}
    <h4>Recent Electrical Parameters in Controller</h4>
    <div class="container-fluid py-3">
        <div class="row">
            {% for parameter in parameters %}
                <div class="col-3 mb-3">
                    <a href=" {% url 'controller:controller_detail' parameter.controller.id %}" class="text-decoration-none text-dark" title="Click to view {{ parameter.controller.name }}'s recent parameters">
                        <div class="card" style="width: 15rem; height:19rem;">
                            <div class="card-body">
                                <h5 class="card-title">
                                    {{ parameter.controller.name }}
                                </h5>
                                <small class="text-muted"><small><i>{{ parameter.created }}</i></small></small>
                                <hr>
                                <ul class="list-group list-group-flush" style="font-size: smaller;">
                                    <li class="list-group-item text-muted">RMS Voltage: {{ parameter.rms_voltage }} V</li>
                                    <li class="list-group-item text-muted">RMS Current: {{ parameter.rms_current }} A</li>
                                    <li class="list-group-item text-muted">Active Power: {{ parameter.active_power }} W</li>
                                    <li class="list-group-item text-muted">Reactive Power: {{ parameter.reactive_power }} W</li>
                                    {% if parameter.phase_connection %}
                                        <li class="list-group-item text-muted">Phase Connection: {{ parameter.phase_connection}}</li>
                                    {% endif %}
                                </ul>
                            </div>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
                  
    </div>
{% endblock %}

controller/templates/controller/detail.html
{% extends 'base/base.html' %}
{% load static %}

{% block content %}
<h4>Electrical Parameters of {{ controller.name }} (Recent 10 datas)</h4>
<div class="container-fluid py-3">
    <table class="table table-striped">
        <thead>
          <tr>
            <th scope="col">Timestamp</th>
            <th scope="col">RMS Voltage</th>
            <th scope="col">RMS Current</th>
            <th scope="col">Active Power</th>
            <th scope="col">Reactive Power</th>
            {% if not master %}
                <th scope="col">Phase Connection</th>
            {% endif %}
          </tr>
        </thead>
        <tbody>
            {% for param in parameters %}
            <tr>
                <th scope="row">{{ param.created }}</th>
                <td>{{ param.rms_voltage }}</td>
                <td>{{ param.rms_current }}</td>
                <td>{{ param.active_power }}</td>
                <td>{{ param.reactive_power }}</td>
                {% if param.phase_connection %}
                <td>{{ param.phase_connection }}</td>
                {% endif %}
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}